import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; 
import { AuthProvider } from '@/context/AuthContext';
import { Toaster } from 'sonner';

import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Navbar /> {/* ✅ El Navbar ahora se muestra en todas las páginas */}
        <main>{children}</main>
        <Footer />
         <Toaster richColors position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
